### PR TITLE
Add XDG_CONFIG_DIRS, close #29

### LINKED ISSUE #29: Confuse doesn't fully support the XDG Base Directory specification
See https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

It should fall back to `$XDG_CONFIG_DIRS`  when there is no local config. It should likely also expose `$XDG_DATA_HOME`, but i'm not sure how

### PR DESCRIPTION
**Pull request by bubylou**
Signed-off-by: Nicholas Malcolm <bubylou7@gmail.com>

### CODE REVIEW

**Comment by bubylou** [comment]
The [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) says that the `XDG_CONFIG_DIRS` environment variable should default to `/etc/xdg` if not set. This is an issue because confuse attempts to create these directories in [config_dir()](https://github.com/sampsyo/confuse/blob/d4ab55771649c21e1650331382b97d8cc9f956c1/confuse.py#L925-L956) on line 955 if they do not already exist but on most systems `/etc/xdg` can only be written to by root so it raises an `OSError`. Should this behavior be added to fully conform to the spec and if so what should be done about the error?

**Comment by sampsyo** [comment]
Looks perfect; thank you! But instead of duplicating those two lines in the two functions, could you please put them into a little function of their own?

(Also, do we need to worry about escaping `:`? Probably not, but just thought I'd ask…)

**Comment by bubylou** [comment]
I did move this to a separate function and the `:` does not need to be escaped. Any thoughts on my comment above or did you want to pull as it is now?

**Comment by sampsyo** [comment]
Looks excellent! Thank you again!!

**Pull request merged**
